### ISSUE TITLE
Return uri instead of hash with uri

### ISSUE THREAD

**Issue by r38y** [infowrap/filepicker_client#3]
As I was looking through the code I noticed there was a lot of `second_file.file_read_uri[:uri]`. How do you feel about making it so that those methods return the uri directly? I feel like a method with that name should return a uri, not a hash with a uri.

**Comment by r38y** [comment]
Oh I see it is returning the expiration too. I'm not sure what to do about that, it seems like maybe the method should have a different name. I'm not sure what though. The expiry is kind of out-of-band.

**Comment by adafair** [comment]
Good point. I changed the method names to "file_read_uri_and_expiry" to add a little more clarity: https://github.com/infowrap/filepicker_client/commit/bd03ddcdfebaff818ee795f5bdfa2057b461e20e

It's a little wordy, but I think it gets the idea across.

I've found that usually when I need a URI generated for reading a file, I need to know when that URI expires so it can be refreshed. Adding a second method that just returns the URI might be a good idea in case others don't need to know the expiry, perhaps due to setting it to a time far in the future, but it's easy enough to extract just the URI from this call's return value.
